### ISSUE TITLE
Support for non-Euclidean domains

### ISSUE THREAD

**Issue by IsakFalk** [JuliaGaussianProcesses/KernelFunctions.jl#10]
What is the scope of this project in terms of domains?

There are many kernels on more structured domains, such as
- [Strings](https://en.wikipedia.org/wiki/String_kernel)
- [Graphs](https://en.wikipedia.org/wiki/Graph_kernel)
- [Distributions](https://en.wikipedia.org/wiki/Kernel_embedding_of_distributions)
- [Manifolds](https://en.wikipedia.org/wiki/Kernel_embedding_of_distributions)
- and more

It's probably a large undertaking to implement all of this in a standardised way, but some of these cases have special instances which reduces to operations on arrays of higher order (including subtypes of `Vector{<:Real}` and `AbstractMatrix{<:Real}`).

**Comment by willtebbutt** [comment]
As far as I'm concerned this project should place no restrictions on the domains for which it allows you to implement kernels.

That's not to say that _we_ should implement all of the kernels -- we should implement as few as is required to iron out any kinks in the API, so that we / anyone else who fancies it can implement new kernels later on.

In terms of avoiding constraints, the only real challenge is in deciding how to implement `KernelFunctions.kernel_matrix`. [Stheno.jl](https://github.com/willtebbutt/Stheno.jl) solves this by requiring that all inputs to its equivalent `pairwise`, or `pw` for short, subtype `AbstractVector`.

e.g.
```julia
x1 = randn(11)
x2 = randn(13)
pairwise(matern32(), x1, x2)
```
for stuff defined on R,
```julia
x1 = ColVecs(randn(N, 11))
x2 = ColVecs(randn(N, 13))
pairwise(matern32(), X1, X2)
```
for stuff defined on R^`N`, where a `ColVecs <: AbstractVector` is a lightweight wrapper around the underlying matrix that indicates said matrix should be treated as a collection of length-`N` column vectors.

This means that inputs for "base kernels" ([exponentiated quadratic](https://github.com/willtebbutt/Stheno.jl/blob/61236affc381d5cba16fab67b9a0d93226e8995d/src/gp/kernel.jl#L76), [Matern](https://github.com/willtebbutt/Stheno.jl/blob/61236affc381d5cba16fab67b9a0d93226e8995d/src/gp/kernel.jl#L136), etc) can be abstractly typed, delegating responsibility for determining whether the particular input is valid to the metric (see e.g. [here](https://github.com/willtebbutt/Stheno.jl/blob/61236affc381d5cba16fab67b9a0d93226e8995d/src/gp/kernel.jl#L80) - it's defined for whatever `SqEuclidean` is defined on).

Similarly, the inputs to "combinator" / "composite" kernels can also be completely abstractly typed e.g.

-[Sum](https://github.com/willtebbutt/Stheno.jl/blob/61236affc381d5cba16fab67b9a0d93226e8995d/src/gp/kernel.jl#L371)
-[Product](https://github.com/willtebbutt/Stheno.jl/blob/61236affc381d5cba16fab67b9a0d93226e8995d/src/gp/kernel.jl#L393)
-[Scaled](https://github.com/willtebbutt/Stheno.jl/blob/61236affc381d5cba16fab67b9a0d93226e8995d/src/gp/kernel.jl#L410) (for giving kernels non-unity variance)
-[Stretched](https://github.com/willtebbutt/Stheno.jl/blob/61236affc381d5cba16fab67b9a0d93226e8995d/src/gp/kernel.jl#L438) (for general linear transformations of inputs / giving kernels non-unity length-scale)

In this sense there are _no_ restrictions on what you can implement a kernel to handle, but any particular "base" kernel will either implicitly or explicitly impose constraints on what it knows how to deal with. Needless to say, I like this approach and am in favour of adopting it here.

**Comment by theogf** [comment]
Given the last refactoring we don't have the restriction on Euclidean domains anymore, I am closing the issue.
