### ISSUE TITLE
SqExponentialKernel naming inconsistent

### ISSUE THREAD

**Issue by willtebbutt** [JuliaGaussianProcesses/KernelFunctions.jl#184]
The `SqExponentialKernel` is inconsistently named in that, in this package, we opt for verbose names rather than abbreviations.

I propose to rename this kernel to `SquaredExponentialKernel`, and to deprecate `SqExponentialKernel` over the course of a minor release cycle.

What would people think to this idea?

**Comment by devmotion** [comment]
I like it.

BTW currently there exist 3 aliases of `SqExponentialKernel`, namely `RBFKernel`, `GaussianKernel`, and `SEKernel`, which are also all exported. I'm wondering if we should keep them, or if we want to focus on one specific name for this kernel. Otherwise, `ExponentiatedQuadraticKernel` would be another possible alias :wink:

**Comment by theogf** [comment]
I am against it :) I think there should be a good balance between verbose and abbreviation. And `SquaredExponentialKernel` is definitely too verbose, I think people understand what is meant with `SqExponentialKernel` or at least we did not get any complains! If it ain't broke don't fix it! :smile: 
Same for the aliases, I think the `SqExponentialKernel` has a special place since it is THE most common kernel used!

**Comment by willtebbutt** [comment]
> Otherwise, ExponentiatedQuadraticKernel would be another possible alias 😉

I'm very much in favour of this alias, but balanced with my preference to avoid having a millions aliases for the same thing, I would be reluctant to add another.

> And SquaredExponentialKernel is definitely too verbose, I think people understand what is meant with SqExponentialKernel or at least we did not get any complains!

I can certainly see your point. I wonder whether we would recieve complaints about this, or whether people will just put up with it because it's not sufficiently annoying to actually open an issue about.

In any case, I'm happy to close this issue until such a time that we _do_ recieve complaints (other than my own :joy:)
