### ISSUE TITLE
CI not cancelled when new commit pushed

### ISSUE THREAD

**Issue by willtebbutt** [JuliaGaussianProcesses/KernelFunctions.jl#281]
I've been commiting lots of stuff in #280 , thereby generating a very large number of jobs for CI to churn through.

Is there a way to ensure that existing jobs on a particular branch are cancelled when someone pushes a new commit?

edit: for example, [our actions page](https://github.com/JuliaGaussianProcesses/KernelFunctions.jl/actions) is now flooded with CI for tiny docs udpates.

**Comment by devmotion** [comment]
AFAICT (e.g., https://github.community/t/is-it-possible-to-cancel-previous-jobs-automatically-when-the-pull-request-is-updated/16779/5 and https://github.community/t/github-actions-cancel-redundant-builds-not-solved/16025) such a feature is not supported by Github actions. However, it seems some people created custom actions for this purpose which one could maybe use. Since I haven't looked into this more carefully, I don't know which one is recommended though.

Of course, an alternative would be to not push after each commit if there are many more to come or to cancel jobs manually if they are not needed anymore.

**Comment by devmotion** [comment]
Seems to be addressed by https://github.com/JuliaGaussianProcesses/KernelFunctions.jl/pull/292.
