### ISSUE TITLE
lengthscale transform

### ISSUE THREAD

**Issue by st--** [JuliaGaussianProcesses/KernelFunctions.jl#326]
There is currently ScaleTransform, ARDTransform, and LinearTransform. These could all be unified under a LinearTransform with potentially specialised matrices (e.g. a scaled identity matrix or a diagonal matrix for ScaleTransform or ARDTransform, respectively).

Moreover, other kernel/GP packages generally parametrise the kernels with the rather more interpretable _lengthscale_ rather than the inverse lengthscale as KernelFunctions.jl does at the moment: it would be good to have an easy way for users to directly specify a lengthscale (ARD or not).

**Comment by devmotion** [comment]
I think the ScaleTransform is sufficiently different from the others since it does not operate on vectors necessarily.

Regarding ARDTransform, this was discussed in https://github.com/JuliaGaussianProcesses/KernelFunctions.jl/issues/107.

Length scale was discussed in https://github.com/JuliaGaussianProcesses/KernelFunctions.jl/issues/217#issuecomment-760995803, it seems the issue shouldn't have been closed since this was not resolved/implemented.

**Comment by devmotion** [comment]
The lengthscale issue is fixed by https://github.com/JuliaGaussianProcesses/KernelFunctions.jl/pull/336.
