### ISSUE TITLE
Moving KernelFunctions.jl to the GPMLj organisation

### ISSUE THREAD

**Issue by theogf** [JuliaGaussianProcesses/KernelFunctions.jl#46]
Should we move ownership to the GPMLj organisation? I think that would make a lot of sense but I am not sure how the collaborator thingy would go?

**Comment by devmotion** [comment]
Recently I transferred the EllipticalSliceSampler package to the TuringLang organization. That was quite straightforward, I just followed the steps on Github. IIRC all collaborators of the original repo are automatically also collaborators of the transferred repo. Additionally, I just made a manual PR to the registry that updated the URL (although not strictly necessary since Github will forward requests to the new destination).

A side from that, I think the name GPMLj is a bit strange - maybe that should be changed to GPJ (similar to MLJ) or JuliaGP (similar to JuliaDiffEq)?

**Comment by theogf** [comment]
This was raised already by @willtebbutt : https://github.com/GPMLj/GPMLj.jl/issues/16 . Apparently they did not accept such a short name. I guess JuliaGP is much better (although the guidelines says to avoid havng julia in the name)

**Comment by devmotion** [comment]
Yes, I saw that discussion but actually here I was thinking more about the name of the organization, not the package (even though that name is also a bit strange IMO).

**Comment by theogf** [comment]
Oh yeah I see the point That's a very good idea.

**Comment by willtebbutt** [comment]
Yeah, lets wait for the org name to be sorted out -- I think JuliaGP is an excellent choice -- and then move KernelFunctions over if there are no objections.

**Comment by sharanry** [comment]
I think the org name has been sorted out now. Is now a good time to move it if no one as any objections?

**Comment by theogf** [comment]
Yes! I will move it during this week

**Comment by theogf** [comment]
It has been now moved! Good bye little one! :cry:
